name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./app

      - name: Create production build
        run: npm run build
        working-directory: ./app

      - name: Create CNAME
        run: echo "iseclassdown.ca" > build/CNAME
        working-directory: ./app

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./app/build
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
        
      - name: Deploy production build
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
